### ISSUE TITLE
Customer Meeting on June 3, 2022

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#103]
## User story
1. As a PO
2. I want / need to conduct the meeting with our customer
3. So that we can demo our current progress and ask specific questions

## Agenda for the meeting

- Demo of the current status of the app by one SD (@Chippelius presents)
- Discussion regarding features/prioritization/organization, including: 
- #105 --> BLE devices vs. Bluetooth devices | BLE devices from industry partner
- email from June, 01 2022 (#104) and email from June, 02 2022
- Open discussion regarding technical questions

## Who will attend? 
Please check if you attend the meeting. 
- [ ] @cynthiachen28 
- [x] @Meisterlu 
- [x] @codingwithelijah 
- [ ] @domi1504 
- [x] @Chippelius
- [ ] @Interperle 
- [x] @Wandinad 
- [ ] @jannikbmc 
- [ ] @NicoStellwag

**Comment by jannikbmc** [comment]
As always i cannot attend it, because i am working that day.

**Comment by codingwithelijah** [comment]
@SDs: If you have any questions, that could be also interesting to clarify from a business perspective, just post them here. Then I will add them in the discussion with the customer. :)

**Comment by codingwithelijah** [comment]
Things to discuss: 
#105 --> see comment from @Chippelius
