### ISSUE TITLE
Take care of email from customer, June 01, 2022 - 11.11 am.

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#104]
- Build-pipeline Bug
- Headline Bug

**Comment by jannikbmc** [comment]
headline bug fixed - awaiting pull request :)

**Comment by codingwithelijah** [comment]
@Chippelius and @jannikbmc: Have you already answered the email from our industry contact? If not, we have time to clarify it in tomorrow´s meeting. We can also discuss a new e-mail which just arrived a couple of seconds ago. 
Please give me a thumbs up if you agree.

**Comment by jannikbmc** [comment]
No, we said yesterday, to simply add tomorrow, that we integrated his suggestions and thank him for his email, in order to not increase the email flood.
