### ISSUE TITLE
Create Bill of Materials (Tab in Planning Document)

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#13]
**Disclaimer**: Will be complemented along the project, does not need to perfect yet

## User story
1. As a team
2. We need to initialize Bill of Material with our dependencies
3. So that we have a centralized source of information needed for software development

## Acceptance criteria
* Add dependencies to Planning Document

**Comment by NicoStellwag** [comment]
Adrian + Jannik: Runtime Components
Nico: Technology Stack, Bill of Materials
Marib: Code Components
