### ISSUE TITLE
[DUE ON FRIDAY] Research regarding BLE vs Bluetooth

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#138]
## User story
1. As a user
2. I want / need to understand the functionalities of the app
3. So that I know which devices I can track within the app and can use it correctly

## Acceptance criteria

- [x] - Find out if we can pair with BLE devices within the Bluetooth settings of the smartphone (only BLE not BLE + Bluetooth)
- [x] - Research on how to identify BLE devices and do their identifiers change and inform POs (either via comments or schedule short meeting)

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by NicoStellwag** [comment]
### General information:
- 2 ways of connecting possible
    - pairing: keys are exchanged and used for only one session
    - bonding: keys are exchanged and saved in some internal db
- pairing is called connect in our framework
- bonding is not possible via our framework
    - the framework does expose the native xamarin objects
    - those can be used to bond
    - other alternative: switch ble library to shinylib
    
### Regarding the first point (smartphone's bluetooth settings):
- iPhone
    - shows bonded ble devices and lets the user delete them
    - does not show them when scanning (bonding only possible via code in third party apps)
- Android
    - shows BLE devices (most of them cannot be connected to without an extra app, though)

### Regarding the second point (guid changes):
- guids of BLE devices can change, but it's less common than with normal bluetooth
