### ISSUE TITLE
Create draft of standalone UI

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#14]
## User story
1. As a SD
2. I want / need to create a first UI-design of the APP
3. So that I can demonstrate a first running UI 

## Acceptance Criteria
- [x] * UI includes all basic components of the app
- [x] * Don´t go into too much detail here
- [x] * Rather focus on the overall concept of the UI
- [x] Take both UI drafts (see comments #15 , combine good ides and decide on one UI
- [x] Add structure within app after confirmation of draft by POs

## Further description
- see also #15

**Comment by Interperle** [comment]
We'll present both final drafts at our industry partner meeting on Friday and then vote for the final draft together with the industry partner. So we also have their opinion about it.

**Comment by codingwithelijah** [comment]
@Interperle: Great! Just contact me before friday on your current status ... then I can consider that when planning the agenda for the meeting on friday :)

**Comment by jannikbmc** [comment]
**Current Visualization of the UI**

![photo_2022-05-24_01-18-26](https://user-images.githubusercontent.com/52490096/169919500-11faebe4-8038-4db2-a028-f8dc6c679b5e.jpg)
![photo_2022-05-24_01-18-27](https://user-images.githubusercontent.com/52490096/169919508-7582afcc-f752-424a-853f-7397ca6f9e48.jpg)
![photo_2022-05-24_01-18-28](https://user-images.githubusercontent.com/52490096/169919515-c145ffb9-184f-4680-ab8a-b827348eb9d8.jpg)
![photo_2022-05-24_01-18-28 (2)](https://user-images.githubusercontent.com/52490096/169919522-1104786d-716a-4d18-9f11-7e74c4860453.jpg)
![photo_2022-05-24_01-18-29](https://user-images.githubusercontent.com/52490096/169919525-8b0529ec-af1c-4c17-9969-9adc07db269f.jpg)
![photo_2022-05-24_01-18-30](https://user-images.githubusercontent.com/52490096/169919530-1e162d0b-d962-4e13-b8e0-c42ca828212c.jpg)
