### ISSUE TITLE
Create Sitemap

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#15]
## User story
1. As a SD
2. I want / need to create a Sitemap
3. So that the team understands the construction of the App

## Acceptance criteria

- [x] * all views included
- [x] * visualization that shows how views are connected
- [x] * includes all ideas from the business partner (see presentation from BP) and is extended by own ideas

## Comments from the Team Meeting
* It is up to the assignees which format/tool they use

**Comment by Interperle** [comment]
We (@Chippelius and me) created two sitemap drafts. The design depends on the GUI-structure, but they're quite similar. Both drafts are changeable and extendable:

1. Draft:
This draft is used in case we're using a one pager for navigation and not a "classical" (top-/bottom-) bar. Leo will present this draft on Wednesday.

![sitemap_2](https://user-images.githubusercontent.com/54355232/168460735-1031928c-9128-4c7c-a7de-f3496c7b6fb4.png)

2. Draft:
This draft is used in case we're using a "classical" (top-/bottom-) bar for navigation. Marib will present this draft on Wednesday.

![sitemap_1](https://user-images.githubusercontent.com/54355232/168460746-6647edfa-9269-4cda-97a1-6da8b6f3731b.png)

**Comment by Interperle** [comment]
FYI: 
The setting page "About the project" will contain some information about AMOS, our Licence and the Link to our Github Repository.

**Comment by Chippelius** [comment]
I created a draft for a possible UI for our app. You can find it here: 

https://chippelius.github.io/FindMyBLEDevice-UI-Draft/ 

If you re-visit it after some time (and something looks off), be sure to press Ctrl + F5 to make sure you clear any cached style data!

**Comment by Interperle** [comment]
Here's the sketch for the second draft:
https://www.figma.com/file/wEc70eFPQ9WLWrNjvW1pat/FindMyBLEDevice?node-id=0%3A1

If you have problems with opening it, please contact me
