### ISSUE TITLE
Establish knowledge base

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#16]
## User story
1. As a team member
2. I want / need to transparently share my knowledge
3. So that the whole team knows what kind of knowledge already exists in the team. 

## Acceptance criteria
* Upload filled out form of knowledge base
* See path: Documentation/knowledgebase/Knowledgebase template.md
* Upload your document titled "knowledgebase_firstname_lastname"
* Due date: **by the end of the week (Sunday)**

## Status Quo
- [x] Xiangxiang
- [x] Luis
- [x] Elias
- [x] Leo
- [x] Dominik
- [x] Adrian
- [x] Jannik
- [x] Marib
- [x] Nicolas

**Comment by Meisterlu** [comment]
Quick reminder: @cynthiachen28 @Chippelius @Wandinad @jannikbmc. Please add your file to the documentation folder as described above. If done already please the check yourself. within the status quo
