### ISSUE TITLE
ViewModel-Tests 

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#201]
## User story
1. As a SD
2. I want / need meet the requirements set by the customer
3. So that we have a successful collaboration with happy customers in the end

## Acceptance criteria

- [x] * Write tests to cover the viewmodel-components of our app
- [x] * Make sure to improve the overall test code coverage by a substantial amount of percentage points

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by codingwithelijah** [comment]
@Chippelius and @jannikbmc: Could you give us a quick update regarding the progress of this issue? Thanks in advance :)

**Comment by Chippelius** [comment]
Thank you very much! 
I will discuss with the POs later whether it should already be merged or not (since my refactoring also isn't really done yet, just like the tests).
