### ISSUE TITLE
Prepare scenarios for and conduct regression tests

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#210]
## User story
1. As a User
2. I want / need to use an app that runs without bugs
3. So that I enjoy using the app and are not annoyed by occurring bugs

## Further description
- We want to make 100 % sure, that the final app runs without any bugs. Keep Marcus´ words in mind: "Stop Starting - Start Finishing". That´s why we want to take care of this concern early
 
## Acceptance criteria
- [ ] Write test scenarios for the usage of the entire app
- [ ] Each test scenario should have a title, a short description what to do, an expected behavior and an actual behavior
- [ ] Create an excel file with all the test scenarios and various columns for "actual behavior" 
- [ ] For each column "actual behavior", prepare a cell where the test taker can enter his name, date and time of test execution, description of used hard- and software
- [ ] Upload Excel-File to GitHub
- [ ] If "expected behavior" is unclear, contact POs
- [ ] Make sure to run one test run 

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Chippelius** [comment]
@codingwithelijah @Meisterlu Please don't ask for an excel file, because it is a binary file format. 
Alternatives would be a markdown file (containing a table) or, if you really want nothing except a table, a csv file.
