### ISSUE TITLE
Make explorative Tests

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#211]
## User story
1. As a User
2. I want / need to use an app that runs without bugs, regardless of my prior knowledge
3. So that I enjoy using the app and are not annoyed by occurring bugs

## Further description
- We want to make 100 % sure, that the final app runs without any bugs. Keep Marcus´ words in mind: "Stop Starting - Start Finishing". That´s why we want to take care of this concern early
- Some edge cases already mentioned in initial presentation sent to us by Markus

## Acceptance criteria
- [x] Try to find out how the software actually works and ask questions about how it handles difficult and simple cases
- [x] Be creative in what values to enter, which paths to take, ...
- [x] Prepare a summary in a format of your preference where you let the whole team know, which cases you considered, what the expected behavior was and which improvements you would suggest

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Interperle** [comment]
Current status: https://github.com/amosproj/amos2022ss05-find-my-hearing-aid/blob/explorative-tests/Documentation/explorative_tests.md
