### ISSUE TITLE
Ensure well-refactored code

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#213]
## User story
1. As a SD
2. I want / need to provide the customer with well-written code
3. So that our code is understandable and can easily be extended by other developers

## Acceptance criteria
- [x] No duplicate code
- [x] Not too many nestings
- [x] Use your own "clean code"-understanding to refactor what is possible

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Interperle** [comment]
Even if it's not code, I also reviewed some of the Issues.
@codingwithelijah and @Meisterlu could you please have a look at the following issues if they're still needed?
https://github.com/amosproj/amos2022ss05-find-my-hearing-aid/issues/25
https://github.com/amosproj/amos2022ss05-find-my-hearing-aid/issues/23

**Comment by NicoStellwag** [comment]
@Chippelius
I think the change to the navigator object destroyed the new stack / push on existing stack situation.
We might want to merge the branch 227-reachable-notification into the viewmodel test branch, I already implemented starting a new stack there because we needed it for the issue.

**Comment by Chippelius** [comment]
@NicoStellwag In what sense did it "destroy" the new stack / push on existing stack situation? 
And concerning branch 227-reachable-notification, while I do like the bool option to create a new stack, I'm not happy with the way you implemented the reachable notification itself: ViewModels are, by refactoring standard, not allowed to access the App class. Also, the way the UpdateService event works is off, it shouldn't pass a device list as arguments, but the viewModel should keep its own local device list (updated by the DevicesStore-Event) and just get the device with its WithinRange status from that list. 
And why is it called ForegroundService now?

**Comment by NicoStellwag** [comment]
> 

Transitions that previously opened a new stack don't do so anymore. (See maps button of the device list for example)

**Comment by NicoStellwag** [comment]
> Yes, calling it a foreground service was a mistake by me. I since then found out and gave the service a different name, but didn't have a good opportunity to communicate that back, yet.
> 
> Yes, everybody owns the whole codebase and calling the branch private obviously wasn't right, but apparently I still have a different understanding of collaboration on a branch. Up until now, whenever I was working on one, either I was the only one working on it or I had direct communication with the other collaborator before /during any changes. And from this, in combination with being the release manager so often, I may have developed a false sense of ownership over branches.
> 
> And I realized that my tone was too harsh, which is why I did edit it. If I meant it that way, I wouldn't have edited it. If you felt like not being treated as an equal or even insulted by my message, I am sorry and I assure you that was not my intention.

It's all right, I also got a little emotional when first reading your comment and would probably formulate some things different now. Let's talk about how to resolve the upcoming merging issues and handle the branches in the future some time at the weekend! :)

**Comment by codingwithelijah** [comment]
> Even if it's not code, I also reviewed some of the Issues.
> @codingwithelijah and @Meisterlu could you please have a look at the following issues if they're still needed?
> #25
> #23

@Interperle: Thanks for the note, @Meisterlu and I have this on the screen.

**Comment by codingwithelijah** [comment]
@NicoStellwag and @Chippelius: Love the spirit from both of you, guys! Good, to see that you are involved also with your feelings in THE AMOS PROJECT! 😅😅

However, let us now put our minds at ease. Talking to each other is often a good option to prevent misunderstandings! 😎😎😎
I hope you were able to clarify the issue and we rock our project together on the last meters without catfights. 🐈
