### ISSUE TITLE
  Confirmation dialogue within device detail view

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#219]
## User story
1. As a user
2. I want / need be reminded if i really want to change or delete the name of the device
3. So that I dont accidentally change something did not intend to do so 

## Acceptance criteria
- [x] when changing the name of the device, the user should be asked if he really want to change it
- [x] same applies when the user wants to delete it 
- [x] when clicked on accept it should provide the intended change

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by domi1504** [comment]
https://user-images.githubusercontent.com/25779097/176859261-52a29527-e930-4855-a40e-8adcda51f58f.mp4

**Comment by domi1504** [comment]
The confirmation-dialogs are ready ;)

**Comment by codingwithelijah** [comment]
> The confirmation-dialogs are ready ;)

Thanks for the update, @domi1504 and @Interperle! Looks good from our side! :)
