### ISSUE TITLE
Storyline for Demo-Day: What scenarios to include and how to approach them?

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#228]
## User story
1. As a team
2. We want / need have a great demo day presentation
3. So that we finish the project in style

## Acceptance criteria
- [x] POs and one SD have a meeting and think about what scenarios we could show and how we can implement them
- [x] create a documentation and update the rest of the team to have common understanding

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Meisterlu** [comment]
[Possible Structure Demo day.pdf](https://github.com/amosproj/amos2022ss05-find-my-hearing-aid/files/9096399/Possible.Structure.Demo.day.pdf)
