### ISSUE TITLE
Revise design and build documentation in our wiki

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#234]
## User story
1. As a customer
2. I want / need be able to have a proper documentation of the software
3. So that I am able to build upon the project and comprehend what has been done so far

## Acceptance criteria
- [x] Update the user documentation with the current state (PO)
- [x] Include the geolocation feature explanation into the user docuemntation (PO)
- [x] Update the design documentation in our WIKI (SD)
- [x] Update the build and deploy documentation in our WIKI (SD)
- [ ] Add relevant information in the "README"-file in our GitHub Repo (SD + PO)

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by codingwithelijah** [comment]
@domi1504: For your SD-part documentation: Please have in mind that it is not required to spend too much time on this issue. Rather make sure, that all the information we so far published in our Wiki is consistent with what you have implemented as SDs.
