### ISSUE TITLE
Create Demo Day Slide

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#246]
## User story
1. As a team
2. We want / need to briefly display our core project idea on one slide
3. So that other people quickly get an overview of our project

## Further description: 
Description from deliverables: 
- Create one overview slide of your project for inclusion in the demo day introduction.
- This can be sparse: Project idea, a screenshot, team photo, logo. (Real content is in demos.)
- This is not necessarily the slides you may use at your demo; in your demo you can use others.

## Acceptance criteria
- [x] Create one [demo day slide](https://docs.google.com/document/d/1Lfi9pyeh-xWk1wJCQhiwSFgJIl6zEdHNs6-yTb9BWYw/edit#heading=h.tulpy28bs8f8) and upload to Deliverables folder
- [x] Make it a landscape PDF of proportions 16:9 (screen size)
- [x] Name and upload file to sprint-12/demo-day-slide.pdf

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Meisterlu** [comment]
@all as mentioned on whatsapp, please send me your picture for the demo day slide via mail: l.gantikow@gmx.de
