### ISSUE TITLE
[DUE: SAT] Provide summary of last remaining To Dos

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#249]
## User story
1. As a SM
2. I want / need to summarize the last To Dos of the Amos project within this issue
3. So that we as a whole team don´t forget important deadlines

## Acceptance criteria
- [ ] Go through the "Amos deliverables"-document and summarize all remaining To Dos for Sprint 12, 13 and 14 as To Do List in the section below. 

## Last Remaining To Dos: 
**Sprint 12, DDL: 19/07**
- [x] One demo day slide | PO
- [x] Demo day video| PO & Devs(for the software architecture)
- [x] Create a zoom link for demo day and send it to the teachers | SM
- [ ] Prepare the slides deck for demo in 20 mins | PO 
- [x] Set a final meeting time before the demo day(27/07) | SM

**Sprint 13, DDL: 26/07**
- [ ] Finalize user, (technical) design, and build/deploy documentation | Devs and POs
- [ ] Clean up and finish final project release plan | POs
- [ ] Tag code with final-project-release | The release manager

**Sprint 14, DDL: 02/08**
- [ ] [Project summary](https://docs.google.com/document/d/1Lfi9pyeh-xWk1wJCQhiwSFgJIl6zEdHNs6-yTb9BWYw/edit#heading=h.nfd40eij569u) | The team
- [ ] [Project retrospective](https://docs.google.com/document/d/1Lfi9pyeh-xWk1wJCQhiwSFgJIl6zEdHNs6-yTb9BWYw/edit#heading=h.3zoix2xw7s1s) | The team

**The detail explanation of artifacts are in "AMOS Deliverables" document, you can find it [here](https://docs.google.com/document/d/1Lfi9pyeh-xWk1wJCQhiwSFgJIl6zEdHNs6-yTb9BWYw/edit#heading=h.cyxovdydmm60).**

**Comment by cynthiachen28** [comment]
Updates: The Zoom link for the demo day would be the same link as our team meeting link.

**Comment by Meisterlu** [comment]
> Updates: The Zoom link for the demo day would be the same link as our team meeting link.

Alright, thanks @cynthiachen28, and you have sent it to the teachers, right? :)

**Comment by cynthiachen28** [comment]
> > Updates: The Zoom link for the demo day would be the same link as our team meeting link.
> 
> Alright, thanks @cynthiachen28, and you have sent it to the teachers, right? :)

Yes, I sent the link to AMOS team this morning.
