### ISSUE TITLE
Implement guidance based on documentation

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#251]
## User story
1. As a user
2. I want / need be able to have a proper guidance in the app
3. So that I am able to educate myself whenever I do not understand the way the app works

## Acceptance criteria
- [x] Implement the guidance as described in the comments of issue #236 

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jannikbmc** [comment]
Pop ups sehen so aus.


![photo_2022-07-16_16-33-29](https://user-images.githubusercontent.com/52490096/179359220-1a5a3b7d-f232-41fe-9831-8bb2e2301ba3.jpg)

**Comment by codingwithelijah** [comment]
@jannikbmc: Looks great! Implement it.

**Comment by codingwithelijah** [comment]
@jannikbmc: Could you please also add a screenshot of the popup for the "MapSearch"? Want to clarify something ...

**Comment by jannikbmc** [comment]
@codingwithelijah 
![photo_2022-07-18_11-56-29](https://user-images.githubusercontent.com/52490096/179488096-9b352fbc-b4b4-4461-a7cf-2bec088642f7.jpg)
