### ISSUE TITLE
Prepare documentation of app testing

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#255]
## User story
1. As a team
2. We want / need to provide the customer with a detailed description of our testing procedure
3. So that the customer has full transparency on our approach

## Further Description: 
The following acceptance criteria rather serve as a guideline than as strict criteria. We want to make sure, that the above formulated user story is solved. 

## Acceptance criteria
- [x] Prepare a **detailed** description of how we covered testing as a comment in this issue. Address the following points: 
- [x] What components of our app did we test and how?
- [x] Explain the CI/CD-pipeline
- [x] What are the results of our tests?
- [x] How did we approach "writing tests"?
- [x] How did we make sure to cover the whole app with our tests? 
- [x] What are advantages of our testing strategy?
- [x] What are limitations and drawbags of our testing strategy? 
- [x] What would we have done differently the next time? 
- [x] What are lessons learned from testing?
- [x] Provide results in our Wiki under "Design Documentation" --> "Testing" (Heading level 2)

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by domi1504** [comment]
I saved the results in the documentation as requested.
Could you take a look at it?

**Comment by codingwithelijah** [comment]
> I saved the results in the documentation as requested.
> Could you take a look at it?

Hi @domi1504: 
Thanks for your work! Looks good so far ... One comment from my side: Content wise I´m fine with it. Linguistically, however, it still sounds a bit bumpy in some places. It would be great if you could package the content a bit more nicely at one point or another!
