### ISSUE TITLE
Customer Meeting on Friday, July 15, 2022, from 11.00 am

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#264]
## User story
1. As a PO
2. I want / need to conduct the meeting with our customer
3. So that we can demo our current progress and ask specific questions

## Agenda for the meeting
- Demo of the current status of the app by one SD (**who? TBD IN MEETING**)
- We will then just show one slide prepared by POs that shows what our plan for the upcoming 2 weeks is
- Any organizational questions: Demo day? ...?

**Comment by jannikbmc** [comment]
as ususal, I am working

**Comment by NicoStellwag** [comment]
In which meeting do you plan on determining who will present?

**Comment by cynthiachen28** [comment]
Hi, I would attend but I can't tick the box as before. Are we missing the "Who will attend?" part?
