### ISSUE TITLE
Ensure DoD of final release project

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#276]
## User story
1. As a PO
2. I want / need to make sure all criteria for DoD of final release project are met
3. So that we can achieve a high-quality completion of the project with a common understanding of "project completion"

## Acceptance criteria
- [x] Go through DoD of final release project and make sure all criteria are met

## Definition of done (DoD)
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by NicoStellwag** [comment]
@codingwithelijah 
Regarding the technical part of the DoD for the whole project:
- non functional requirements (test coverage...) are met, (at least the updated requirements markus gave us verbally in one of the meetings)
- there's no half-implemented features of any kind or commented code in our codebase

Generally speaking, I would say we are fine.
