### ISSUE TITLE
Bug: Default name in black font --> change to grey font

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#286]
Bug

**Comment by Wandinad** [comment]
@codingwithelijah @Meisterlu 
This is the placeholder color:
![grafik](https://user-images.githubusercontent.com/80949241/179997122-58192aee-a7f8-4f8b-b683-5d9f51628f0b.png)


and this is the standard input color:
![grafik](https://user-images.githubusercontent.com/80949241/179997308-c179c167-6cd3-47f3-8d90-eaef10e31d11.png)

Just a quick confirmation that the color fits

**Comment by codingwithelijah** [comment]
@Wandinad: Perfect! Exactly what we were thinking ...
