### ISSUE TITLE
[I.1 - See device]: Display surrounding BLE devices

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#39]
## User story
1. As a User
2. I want / need to have devices that are in my immediate area displayed
3. So that I can afterwards select devices, assign labels to devices and view already labeled devices. 

## Further Description
* General conditions: Bluetooth is already switched on on finding device and BLE device
* No need to implement any notes that help the user etc. 
* See also: #7 --> comments!
* Please first agree on a approach on how to handle bluetooth-devices within XAMARIN as entire SD-group
* Technical focus, no UI focus

## Acceptance criteria

- [x] * Show a ready-to-use screen of the app that fulfills the following criteria:
- [x] * Button visible that starts searching for nearby BLE devices which are emitting a bluetooth signal
- [x] * Found BLE devices displayed in a table 
- [x] * Sort devices displayed in table in descending order according to signal strength 
- [x] * Add a loop that updates order of BLE devices every second according to received signal strength

**Comment by NicoStellwag** [comment]
technical infrastructure for scanning for devices is pretty much done, all that is left is properly displaying the devices (which we plan on doing later today)

**Comment by NicoStellwag** [comment]
We have a working demo, but I seem to have the same xamarin bug as leo (list items are not shown on the physical phone).

@Meisterlu @codingwithelijah 
Someone will have to look into this in the near future.
Could you include an issue for this in the next sprint?
