### ISSUE TITLE
[I.2 - Select device]: Select one BLE device

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#49]
## User story
1. As a User
2. I want / need select a BLE device in my surrounding
3. So that I can assign a label to the BLE device

## Description
* precondition: #39
* No need for nice design, keep it simple. Only first draft

## Acceptance criteria

- [x] * Show a ready-to-use screen of the app that fulfills the following criteria
- [x] * You can select a BLE device that is in my surrounding
- [x] * Selection of a BLE device is visually encoded on the screen 
- [x] * Selection of a BLE device is stored in the app locally

**Comment by NicoStellwag** [comment]
we will probably have to postpone that to the next sprint (depends on how fast we get the view for issue #39 to work)
