### ISSUE TITLE
Assign label to BLE device

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#51]
## User story
1. As a User
2. I want / need to change the name of the listed BLE device once
3. So that I can remember the name of my device more easily

## Further details
- condition done before: #73 

## Acceptance criteria
- [ ] user has ability to change the displayed name of the selected BLE device and enter an individual name
- [ ] stored locally
- [ ] When user closes the app and returns, app recognizes labelled device

## Definition of Done

- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

**Comment by Chippelius** [comment]
Seems like it, yeah. Then third one as well. 
@codingwithelijah We think this issue is already done, judging by its acceptance criterea.
