### ISSUE TITLE
PO: Meeting with Customer

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#60]
## User story
1. As a PO
2. I want / need to prepare the meeting with our customer on friday, 20.05.22
3. So that we can smoothly guide through the weekly meeting and demonstrate our progress

## Acceptance criteria

- [x] * Prepare an agenda for the meeting on Friday
- [x] * Think about what to present 
- [x] * Talk to the developers in advance
- [x] * Guide through the meeting on Friday
- [x] * Prepare next steps after the meeting

**Comment by codingwithelijah** [comment]
[Update]: Developers will comment their status quo for customer meeting by Friday, 20.05.22, 9.00 am.

**Comment by NicoStellwag** [comment]
I think the only question unanswered is about the Apple Dev Account.
No more questions from my side so far.

**Comment by domi1504** [comment]
Also from my side, no questions at this point. 
If it comes to what we can show, I think our pipeline is the only interesting "presentable" achievement, but I would say it is a big one. We can maybe say that we have a running demo-app with a working sqlite-database, but I don't think that we have to show it to them; I am confident they know how the default demo-app from microsoft looks like :D

**Comment by Chippelius** [comment]
I have questions on two topics: 
* Clarify what exactly they mean by "assigning labels to devices" (Is a label just text? Is there one label per device or can there be multiple? ...)
* Clarify how many different devices should be supported (Only 2 devices overall, like shown on their slides? Or an arbitrary number, like shown in my UI draft?)

Also we as the group of issue #14 want to present our UI draft designs ans ask for the industry partner's opinion on which one to choose. (This could be combined with / used as a transition to my second point from above.)
