### ISSUE TITLE
Regurarly update UI based on extracted signal strength

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#75]
## User story
1. As a user
2. I want / need to see visually how the bluetooth signal of a BLE device changes based on the movement of my own device 
3. So that I get an indication on where the BLE device could be located. 

## Further description
precondition: 
* #74 
* #71 

## Acceptance criteria
- [x] Regularly update the view to indicate distance to selected device
- [x] Connect with created view (#71)

## Definition of Done
- It builds without errors
- code has been reviewed
- Build has been made and deployed on a testing environment
- Code coverage >75%
- All acceptance criteria were met
- Documentation updated whenever needed within planning documents (Tabs: Bill of materials, Documentations)
- Branch/feature was merged into dev and then main

**Comment by NicoStellwag** [comment]
@domi1504 @jannikbmc  @Meisterlu @codingwithelijah 
Quick update:
I connected the circle radius to a rough estimate of what the distance to the device could be.

Still pending: 
- Distance formula is dependent on some constants we need to poll from the device.
This requires us to be connected to the device (which is probably necessary anyway - see markus' mail).
@Wandinad I don't know if you already implemented the strength search button for the scan list. In case you didn't it should be obsolete anyway. 
For us this means:
    - Get rid of the AvailavleBTDevice class and use the IDevice interface provided by the framework in the viewmodel instead. (Object needs to be passed back to the framework to connect).
    - Enable the bluetooth service to actually connect to devices and poll their characteristics (=> check out Gatt model).
- Animate circle transitions.

**Comment by NicoStellwag** [comment]
@domi1504 @jannikbmc 
We might want to use the following library for animations:
https://github.com/OliveTreeBible/Xamarin.Transitions

I will look into it later.

**Comment by Meisterlu** [comment]
@NicoStellwag thank you for the update! So just for my understanding and to avoid misunderstandings, whenever we want to search the device via signal strength solution we need to be connected with to this specific device.

**Comment by NicoStellwag** [comment]
@Meisterlu 
Apparently I misunderstood the meaning of "connect" when researching.
I thought of connecting to a device in terms of persistently pairing it with the smartphone, but all it meant was establishing a communication channel (which we already do to poll the rssi).

Regarding the other points:
- We decided animation of the circle was not really necessary, the gui looks acceptable (for an MVP) as it is
- Polling the additional constants from the devices to normalize the circle size can also be posponed after the mid release

**Comment by Meisterlu** [comment]
@NicoStellwag alright! Makes sense, thank you for the update.
