### ISSUE TITLE
No bluetooth devices listed on new device

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#86]
**Describe the bug**
On Android 12, Devices in the surrounding are only shown if Bluetooth and GPS is activated 

**To Reproduce**
1. Go to Devies Page
2. Click on 'Scan for available devices'
3. No devices are shown

**Expected behavior**
All available bluetooth devies should be displayed in the list

**Smartphone (please complete the following information):**
 - Device: Galaxy S20
 - OS: Android 12
 - Version Sprint4-Release

**Additional context:**
This is not really a bug, but it is suprising for the user that Bluetooth Search needs GPS to be activated. 
Android 12 changed the way permissions work, so we have to check on how to implement it to work there without GPS.

**Comment by codingwithelijah** [comment]
Thought from Industry Partner (27.05.22): Maybe we should check to have **all** permissions or we write code to get all permissions?

No agreement so far. POs discuss it in the next team meeting if we should add this feature.

**Comment by codingwithelijah** [comment]
@Wandinad: You already edited the text, right? If so, please just delete the upper part of the body of the issue.

**Comment by codingwithelijah** [comment]
@Wandinad: As discussed today, please just implement a simple popup that appears when the user has bluetooth not switched on. The popup should inform the user that he needs to switch on Bluetooth for the features of our app to work. No more functionality needed.

**Comment by Wandinad** [comment]
Here is what the Pop-up looks like on Android, depending on which Services are implemented:
![Screenshot_20220705-193451_Find My BLE Device](https://user-images.githubusercontent.com/80949241/177384708-9c72869f-fd4c-401f-aa9e-9fec353114a2.png)
![Screenshot_20220705-193504_Find My BLE Device](https://user-images.githubusercontent.com/80949241/177384712-9c2789d7-1abf-4a1a-9730-df4e6fa28f2d.png)
![Screenshot_20220705-193517_Find My BLE Device](https://user-images.githubusercontent.com/80949241/177384715-455a087c-9dc2-4bad-957d-427421c2bfe7.png)
