### ISSUE TITLE
Check: University Apple Developer Account

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#87]

**Comment by codingwithelijah** [comment]
Hi @cynthiachen28!
When I opened this issue I thought: Maybe it is rather an impediment than product related? What do you think? 
If you agree, I would be very happy if you could assign you to the issue and try to solve it! 
Regards, Elias

**Comment by codingwithelijah** [comment]
@Interperle: Did the app also run on your apple device? Please confirm or deny and provide a short update. Thanks! :)

**Comment by codingwithelijah** [comment]
@cynthiachen28: Could you please provide an update? 

> Hi @cynthiachen28!
> When I opened this issue I thought: Maybe it is rather an impediment than product related? What do you think?
> If you agree, I would be very happy if you could assign you to the issue and try to solve it!
> Regards, Elias

**Comment by cynthiachen28** [comment]
For me, it's not an impediment. We only need to make sure whether we could/would get a developer account or not. 
I asked help from the AMOS team that how other teams in the previous year acted on the similar situation and whether the AMOS team can offer us an account. 
If not, then we can only build the app locally. I think it's understandable.

**Comment by codingwithelijah** [comment]
> For me, it's not an impediment. We only need to make sure whether we could/would get a developer account or not.
> I asked help from the AMOS team that how other teams in the previous year acted on the similar situation and whether the AMOS team can offer us an account.
> If not, then we can only build the app locally. I think it's understandable.

Okay thanks, @cynthiachen28. Then update us as soon as the AMOS team answers :)

**Comment by cynthiachen28** [comment]
Update: 
No available account from the AMOS team side and they suggest us to contact RRZE. I send an email today.

**Comment by cynthiachen28** [comment]
Update: 
We can deploy the app within our group under RRZE help. They would add us in one group and then we're able to download the app on our Apple device. 
- Everyone needs to have an AppleID account.
