### ISSUE TITLE
Create README-File

### ISSUE THREAD

**Issue by codingwithelijah** [amosproj/amos2022ss05-find-my-hearing-aid#88]
1. Luis will create a draft of the content. 
2. Elias will finetune and add it to GitHub Repo. 

- collaboration
- architecture

**Comment by codingwithelijah** [comment]
@Interperle: Thanks for your reminder. Just opened an issue and assigned Luis and myself to it! :)

**Comment by Meisterlu** [comment]
@codingwithelijah Updates within OneNote. Next step upload to GitHub within correct format

**Comment by codingwithelijah** [comment]
Just updated our README-file. 
Waiting for input from @Interperle regarding "GETTING STARTED". Afterwards we can move it to "Done".

**Comment by Interperle** [comment]
Added the "Getting Started"
