### ISSUE TITLE
Create PDF of software architecture description and upload to Deliverables folder

### ISSUE THREAD

**Issue by Meisterlu** [amosproj/amos2022ss05-find-my-hearing-aid#9]
## User story
1. As a team
2. We need a description of the underlying software architecture
3. So we have a common understanding of the software components used in the project

## Acceptance criteria

- An overview diagram of runtime components (one page)
- An overview diagram of code components (one page)
- A summary of the underlying technology stack (one page)
- A textual explanation of the diagrams and choices (one page)

**Comment by NicoStellwag** [comment]
Adrian + Jannik: Runtime Components
Nico: Technology Stack
Marib: Code Components
