### ISSUE TITLE
Opening the "Devices" page twice crashes the app

### ISSUE THREAD

**Issue by Chippelius** [amosproj/amos2022ss05-find-my-hearing-aid#99]
**Describe the bug**
When opening the "Devices" page a second time after having been to a different page since the last time, this second opening causes the app to crash. 

**To Reproduce**
1. Open the app
2. Go to 'Devices' 
3. Go to any other page (e.g. back to 'About') 
4. Go to 'Devices' again 

**Expected behavior**
The "Devices" should open normally again. 

**Screenshots**
It's hard to screenshot the app in the exact moment it crashes. 

**Smartphone:**
 - Device: Galaxy S10+
 - OS: Android 12
 - Version sprint-04-release (and development-versions on their way to sprint-05-release) 

**Additional context**
I think the problem is with the way stored / paired devices are loaded and displayed, not with the available devices. I think this because I remember this bug existing before the scanning for available devices was added. However, I'm not 100% sure about this, so this claim needs to be verified by looking into the git history and trying said version before scanning for available devices was added.

**Comment by domi1504** [comment]
I will take a deeper look into this in the future.
